// <auto-generated />
namespace HospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class LinkPreScreeningToUserId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LinkPreScreeningToUserId));
        
        string IMigrationMetadata.Id
        {
            get { return "202204220126054_LinkPreScreeningToUserId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
