// <auto-generated />
namespace HospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class prescreeningpatient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prescreeningpatient));
        
        string IMigrationMetadata.Id
        {
            get { return "202203250122209_prescreening-patient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
